# This file is machine-generated - editing it directly is not advised

julia_version = "1.11.6"
manifest_format = "2.0"
project_hash = "06c00a1e25a84f98b67d915bdf15e4a825e153e9"

[[deps.Artifacts]]
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
version = "1.11.0"

[[deps.AsyncLog]]
git-tree-sha1 = "3f6382fdac70760e148a58f3d9f51ff1795842fc"
uuid = "b136e949-d42a-4c20-998e-69d09231b44a"
version = "0.1.2"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
version = "1.11.0"

[[deps.CEnum]]
git-tree-sha1 = "eb4cb44a499229b3b8426dcfb5dd85333951ff90"
uuid = "fa961155-64e5-5f13-b03f-caf6b980ea82"
version = "0.4.2"

[[deps.Crayons]]
git-tree-sha1 = "249fe38abf76d48563e2f4556bebd215aa317e15"
uuid = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
version = "4.1.1"

[[deps.DataStructures]]
deps = ["OrderedCollections"]
git-tree-sha1 = "76b3b7c3925d943edf158ddb7f693ba54eb297a5"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.19.0"

[[deps.Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"
version = "1.11.0"

[[deps.DuplexIOs]]
path = "packages/DuplexIOs"
uuid = "c20a4678-4bba-4df2-bd7d-5c4d76fa7d4b"
version = "0.1.1"

[[deps.IOTraits]]
deps = ["Crayons", "InteractiveUtils", "Markdown", "Preconditions", "Preferences", "REPL", "ReadmeDocs", "TextWrap"]
path = "packages/IOTraits"
uuid = "8782331d-1791-483a-a4c8-2712d2c95aed"
version = "0.3.3"

[[deps.InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
version = "1.11.0"

[[deps.JLLWrappers]]
deps = ["Artifacts", "Preferences"]
git-tree-sha1 = "0533e564aae234aff59ab625543145446d8b6ec2"
uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
version = "1.7.1"

[[deps.LibURing]]
deps = ["CEnum", "Liburing_jll"]
path = "packages/LibURing"
uuid = "0de80037-07fc-49d2-a15d-861f8975cc75"
version = "0.1.0"

[[deps.Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
version = "1.11.0"

[[deps.Liburing_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "1e96d63ad5ac09e624fbaad07740166ae10b2654"
uuid = "6524598b-69a8-53ae-b017-622bece5ca95"
version = "2.8.0+0"

[[deps.Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"
version = "1.11.0"

[[deps.LoggingExtras]]
deps = ["Dates", "Logging"]
git-tree-sha1 = "f02b56007b064fbfddb4c9cd60161b6dd0f40df3"
uuid = "e6f89c97-d47a-5376-807f-9c37f3926c36"
version = "1.1.0"

[[deps.LoggingTestSets]]
deps = ["Crayons", "DataStructures", "Dates", "Logging", "LoggingExtras", "Markdown", "Test"]
path = "../LoggingTestSets"
uuid = "c2339e6d-2e7f-4cf9-92d2-844738085fb8"
version = "0.2.7"

[[deps.Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"
version = "1.11.0"

[[deps.MarkdownTableMaps]]
deps = ["Markdown", "ReadmeDocs"]
path = "../MarkdownTableMaps"
uuid = "273d989c-148d-470a-9902-90424cbd1978"
version = "0.1.2"

[[deps.OrderedCollections]]
git-tree-sha1 = "05868e21324cede2207c6f0f466b4bfef6d5e7ee"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.8.1"

[[deps.Preconditions]]
deps = ["Preferences", "ReadmeDocs"]
path = "../Preconditions"
uuid = "059f9e2d-edd5-4920-8ad6-95789b106d09"
version = "0.2.3"

[[deps.Preferences]]
deps = ["TOML"]
git-tree-sha1 = "9306f6085165d270f7e3db02af26a400d580f5c6"
uuid = "21216c6a-2e73-6563-6e65-726566657250"
version = "1.4.3"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"
version = "1.11.0"

[[deps.REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets", "StyledStrings", "Unicode"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
version = "1.11.0"

[[deps.Random]]
deps = ["SHA"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
version = "1.11.0"

[[deps.ReadmeDocs]]
git-tree-sha1 = "6218f9c2cbb5020378d0249036e973084990675a"
uuid = "c63066b3-de92-487d-9da7-7c375a07912b"
version = "0.2.2"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "0.7.0"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
version = "1.11.0"

[[deps.Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"
version = "1.11.0"

[[deps.StyledStrings]]
uuid = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
version = "1.11.0"

[[deps.TOML]]
deps = ["Dates"]
uuid = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
version = "1.0.3"

[[deps.Test]]
deps = ["InteractiveUtils", "Logging", "Random", "Serialization"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
version = "1.11.0"

[[deps.TextWrap]]
git-tree-sha1 = "43044b737fa70bc12f6105061d3da38f881a3e3c"
uuid = "b718987f-49a8-5099-9789-dcd902bef87d"
version = "1.0.2"

[[deps.TypeTree]]
deps = ["InteractiveUtils"]
git-tree-sha1 = "c1adbb6b9d9374babe8975a456f383a37a8e02ec"
uuid = "04da0e3b-1cad-4b2c-a963-fc1602baf1af"
version = "0.3.0"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
version = "1.11.0"

[[deps.UnixLibC]]
path = "../UnixLibC"
uuid = "16dcc055-d1ce-4ed0-becf-2028a2f53a80"
version = "0.1.1"
